### ISSUE TITLE
Bundling of fonts, js, css

### ISSUE THREAD

**Issue by artem-sidorenko** [appernetic/hugo-bootstrap-premium#18]
Hello,

Thanks for a great hugo theme! I migrate my personal blog from octopress to hugo and use your theme there.

Within this theme are some components already bundled (e.g fontawesome), but some not (e.g. angular.js, google fonts). For my sites I usually try to avoid any not needed requests to other sites (performance, stability, privacy..). 

So the question, are you open to have other things here bundled as well? If yes, I could provide some PRs

**Comment by appernetic** [comment]
Hi,
why not. 
In my pop over modal I use angular.js. So I have angular in the static/ folder somewhere.
