### ISSUE TITLE
how can I add trailing slash to tags?

### ISSUE THREAD

**Issue by jave** [appernetic/hugo-bootstrap-premium#27]
Hello,

I would like to add trailing slashes to tags. Currently this is not done. This becomes a problem when deploying in nginx. It can be solved by adding rules to nginx, but I would like to understand how the tag links are generated, and why they are added to links to posts, but not to tags.

**Comment by appernetic** [comment]
This has just been fixed thanks to artem-siderenko. https://github.com/appernetic/hugo-bootstrap-premium/pull/26
