### ISSUE TITLE
Mobile version not working.

### ISSUE THREAD

**Issue by michw** [appernetic/hugo-bootstrap-premium#3]
Looks like theme is not usable on mobile devices.

How to reproduce?
- Go with Windows Phone browser to https://blog.appernetic.io/2016/06/01/appernetic-theme-showcase-gallery/
- Try to click Start the discussion... in disqus comments section.
- You can't start the discussion.

It probably doesn't work with Android/Chrome as well.

**Comment by appernetic** [comment]
I have tested with Chrome on my Mac and when I resize to width: 767px it is not possible to add comments in the Disqus comment field or use the Disqus buttons.  It works in iPad mode 768px wide.

My code is checked with the W3 validator and there are only 2 warnings nothing that can cause this. Here is the link: https://validator.w3.org/nu/?showsource=yes&showimagereport=yes&doc=https%3A%2F%2Fblog.appernetic.io%2F2016%2F06%2F01%2Fappernetic-theme-showcase-gallery%2F

Is Disqus causing this issue?

**Comment by appernetic** [comment]
The issue is with the columns. 

To make it work the Disqus column need to have: 

`<div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">`

and  the right column need to have col-xs-12 col-sm-12 added:  
`<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">`

**Comment by appernetic** [comment]
Fixed!
