### ISSUE TITLE
posible ads?

### ISSUE THREAD

**Issue by ghost** [appernetic/hugo-bootstrap-premium#33]
Sorry for this request..

is posible to add adsense  on the theme site.

this theme is awesome, i like it.

thanks..

**Comment by appernetic** [comment]
Hi,
yes it's possible to add anything you like. A static site is perfect for ad sense. Here you have a blog post describing a possible solution https://bash-prompt.net/guides/custom-html-jugo/.
 
Nice that you like the theme!
