### ISSUE TITLE
Language menu switcher

### ISSUE THREAD

**Issue by boydkelly** [appernetic/hugo-bootstrap-premium#34]
I am trying this out and it looks very good with mulilanguage support, but I can't get the lanuage switcher to work.  I followed the instructions and made the change in the pathnamereplace.js file.  But with that enabled my browser page does these refreshes and flickers constantly.  But I do notice in the js file it says this has been tested with Chrome 36 etc,  This is pretty old.  Is this still working for others?

Also I don't see any discus commenting available, although that's enabled in the conf.

**Comment by appernetic** [comment]
Hi,
you shouldn't have to edit  pathnamereplace.js. 

It gets the configuration from /layouts/partials/base/scripts.html
there you have this:
CONTENTLANGUAGE = {{ .Site.Params.DefaultContentLanguage }}; // used in pathnamereplace.js

I built it a long time ago for Adobe Business Catalyst. But it should still work. I tested it last year.

**Comment by appernetic** [comment]
@boydkelly please don't add two issues in one!

The discus feature will work if you donẗ use it on localhost. There is no other issue for disqus. But please open a new issue if it persist!
