### ISSUE TITLE
Different date formats for each language

### ISSUE THREAD

**Issue by mgei** [appernetic/hugo-bootstrap-premium#37]
Hello. 
I play with language settings but I don't find a simple solution to change the date format per language. E.g. in German it would be "2. Jan 2006" while "2 Jan, 2006" in English.

I can change the format in `data/Formats.yaml`.
I saw that this is then used in `themes/hugo-bootstrap-premium/layouts/partials/modules/page/date.html` and in `themes/hugo-bootstrap-premium/layouts/partials/modules/site/lastupdate.html`. I don't know how to neatly make it language adaptive.
Do you have a solution for this?

Great theme and documentation, thanks for sharing.

**Comment by mgei** [comment]
Sorry, I should have consulted the Hugo documentation first: https://gohugo.io/content-management/multilingual/#customize-dates

**Comment by appernetic** [comment]
Ok, have you solved it?
