### ISSUE TITLE
static home page?

### ISSUE THREAD

**Issue by mclearc** [appernetic/hugo-bootstrap-premium#38]
Is it possible to use this theme with a static home page as the landing page rather than the list of blog posts?

**Comment by appernetic** [comment]
Yes that is quite easy to do. You probably only have to override the theme by adding an index.html in the /layout/partial/ folder. Then in content/ add a _index.md file.

**Comment by mclearc** [comment]
Thanks. I actually ended up modifying `homepage.html` in `layouts` and adding an `index.md` file in `content`. But that did the trick! I also found [this thread](https://github.com/gohugoio/hugo/issues/330) helpful.
