### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by opoyc** [appernetic/hugo-bootstrap-premium#40]
It seems that if the number of posts exceeds the pagination limit, the effect of selecting the next page (that is, #2) redirects to "https://page/2/"

**Comment by appernetic** [comment]
Ok, must be a bug in the pagination partial.

**Comment by appernetic** [comment]
Are you sure you have a baseurl in the config file?

**Comment by opoyc** [comment]
Yes, it was the baseURL, my bad. Thanks
