### ISSUE TITLE
"resources" not defined ERROR

### ISSUE THREAD

**Issue by appernetic2** [appernetic/hugo-bootstrap-premium#45]
I got this error when using the theme with the exampleSite config file:

Building sites … ERROR 2018/08/02 11:22:12 Failed to add template "theme/partials/base/imports.html" in path "/home/ubuntu/newsrv/repo/github_17408926/appernetic-hugo-project/themes/hugo-bootstrap-premium/layouts/partials/base/imports.html": template: theme/partials/base/imports.html:7: function "resources" not defined ERROR 2018/08/02 11:22:12 Failed to add template "theme/partials/base/scripts.html" in path "/home/ubuntu/newsrv/repo/github_17408926/appernetic-hugo-project/themes/hugo-bootstrap-premium/layouts/partials/base/scripts.html": template: theme/partials/base/scripts.html:10: function "resources" not defined ERROR 2018/08/02 11:22:12 theme/partials/base/imports.html : template: theme/partials/base/imports.html:7: function "resources" not defined ERROR 2018/08/02 11:22:12 theme/partials/base/scripts.html : template: theme/partials/base/scripts.html:10: function "resources" not defined ERROR 2018/08/02 11:22:12 Error while rendering "page" in "post/": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at : error calling partial: template: theme/partials/head.html:10:5: executing "theme/partials/head.html" at : error calling partial: template: "theme/partials/base/imports.html" is an incomplete or empty template

How can I solve this?

**Comment by appernetic** [comment]
Solved! Add the missing file style_custom.css in /assets/css or clone the repo.

**Comment by appernetic2** [comment]
Thanx great speed to fix issues
