### ISSUE TITLE
footnotes and toc links not working

### ISSUE THREAD

**Issue by mclearc** [appernetic/hugo-bootstrap-premium#46]
For some reason footnotes and toc links don't work properly. For example clicking on footnote one in a post should take me to `http://myblog/2018/08/my-first-post/#fn:1` but instead goes to `http://myblog/2018/08/my-first-post/#!#fn:1`. Note the extra `#!`. Something similar happens with toc links on pages where a toc is used. Any idea why that `#!` is being pre-pended?

**Comment by appernetic** [comment]
This sounds to me as an Angular issue.

**Comment by mclearc** [comment]
Indeed - disabling angular fixed the issue.

**Comment by appernetic** [comment]
Ok, great that you solved it. We need a more permanent solution I think.  But I close it for now.
