### ISSUE TITLE
Error when bulding with Hugo 0.48

### ISSUE THREAD

**Issue by h0bbel** [appernetic/hugo-bootstrap-premium#48]
Building my site using hugo-bootstrap-premiums works fine with Hugo 0.47, but with Hugo 0.48 I get the following error: 

`Error while rendering "taxonomy" in "": template: _default/list.html:7:31: executing "_default/list.html" at <.Paginator.Pages>: undefined variable: $index`

Any ideas why that might be?

**Comment by sofixa** [comment]
@h0bbel it's due to the fact that Hugo has moved to Go 1.11 since 0.48 : 

https://discourse.gohugo.io/t/range-offset-variable-undefined-in-0-48/14427/4

**Comment by h0bbel** [comment]
I am sure that is correct, but is there a way to fix the theme? I've been looking at it, but I'm clueless when it comes to Go, so I don't know how to rectify it.

**Comment by sofixa** [comment]
Yep, i'll give it a go this week.

**Comment by sofixa** [comment]
@h0bbel i've fixed it in [my fork](https://github.com/sofixa/hugo-bootstrap-premium) and i've created a PR ( #49  ).

Adrian

**Comment by h0bbel** [comment]
Awesome, thanks Adrian — I made the same changes in my copy, and now I'm up and running with Hugo 0.49. Thanks again!

**Comment by appernetic** [comment]
Just got the same error. Checking your PR.

**Comment by appernetic** [comment]
Merged it.
