### ISSUE TITLE
The Theme's Demo on the Hugo Website is missing its Hugo Pipes Assets

### ISSUE THREAD

**Issue by onedrawingperday** [appernetic/hugo-bootstrap-premium#51]
Hi @appernetic 

On the Hugo Themes website the [demo](https://themes.gohugo.io/theme/hugo-bootstrap-premium/) of the [Hugo Bootstrap Premium Theme](https://themes.gohugo.io/hugo-bootstrap-premium/) has its Hugo Pipes Assets missing. 

For a workaround please see the [Common Permalink Issues](https://github.com/gohugoio/hugoThemes#common-permalink-issues) in the updated README of the Hugo Themes repository.

>If you are using Hugo Pipes to publish your theme's resources due to bug gohugoio/hugo#5226 you will need to temporarily use .RelPermalink in the templates, so that these assets are served correctly on the website.

For example change line 29 of `/layouts/partials/base/imports.html/` to:
`<link rel="stylesheet" href="{{ $css.RelPermalink }}" integrity="{{ $css.Data.Integrity }}">`

Please do this change in the theme's templates and let me know.

Thanks!

CC / @digitalcraftsman

**Comment by onedrawingperday** [comment]
Hello again @appernetic your theme was removed from the Hugo website.

If you apply the fix mentioned in this issue feel free to notify us.

We will be more than happy to have the theme added back to the showcase.

Thanks

**Comment by onedrawingperday** [comment]
Your theme was added again with commit https://github.com/gohugoio/hugoThemes/commit/2d9f912db92c3cb2d477a39026e9c9b684da8460

It seems that the problem was due to a bug. See https://github.com/gohugoio/hugo/issues/5226 for the details.

Sorry for the noise.

**Comment by digitalcraftsman** [comment]
@onedrawingperday is this issue already fixed or did I miss something?

**Comment by onedrawingperday** [comment]
@digitalcraftsman No it is not fixed. The earlier commit was reverted because it broke a lot of other themes (and I simply deleted my previous comment here). 

This issue still stands as is.

**Comment by digitalcraftsman** [comment]
I've seen that Bjørn Erik added and later removed this theme due to https://github.com/gohugoio/hugo/issues/5226. What left me irritated was that this issue hasn't been reopened to track the issue that caused the initial removal of this theme.

**Comment by onedrawingperday** [comment]
@appernetic 

Since Hugo 0.52 your theme's demo generates again when the Hugo Themes Site Build Script is executed.

Your theme will appear again on the Hugo Themes Showcase once https://github.com/gohugoio/hugoThemes/pull/510 is merged.

Thanks.
