### ISSUE TITLE
Sidebar Not Visible 

### ISSUE THREAD

**Issue by ashishna** [appernetic/hugo-bootstrap-premium#7]
Unable to see ```sidebar``` on the latest code in master.

Config file snippet:
```
[params]
    # You can use markdown here.
    BrandImage = "http://blog.appernetic.io/images/apperneticlogo.png" #top header brand image.
    Brand = "Enterprise Integration Blog" # brand image alt text.
    topline = "few words about your site"
    footline = "code with <i class='fa fa-heart'></i>"

    # Show a sidebar menu
    showRightSidebar = true
```

**Comment by alex1702** [comment]
this issue is with hugo 0.18 and above. PR #6 will fix this.

**Comment by appernetic** [comment]
Thanks for the PR! Yes, it works in hugo 0.17. I haven't switched to 0.18 yet.

**Comment by appernetic** [comment]
Found out that it's not backward compatible. Changed to lower case and tested with 0.17 and it did not worked. So in the config.toml in the example folder I leave it as it is so it will work in the theme showcase.

**Comment by alex1702** [comment]
in my test it work with 0.17 and 0.18 with the first Version. with isset and config in lowercase

**Comment by appernetic** [comment]
Hm, ok just tested on my Mac with 0.17 and it did not worked with lower case, but I also saw that 0.18 is official so I will change back to lower case in the example folder.

**Comment by appernetic** [comment]
Ok, I have read all in the PR thread now and understand it. I was a bit confused first. So the simple solution was to change to if instead of isset: ```{{ if .Site.Params.showRightSidebar }}```. 
Perfect! 👍
